### ISSUE TITLE
App crashes when trying to start the GameServer

### ISSUE THREAD

**Issue by valentingavran** [SS20-SE2-Monopoly-Team/monopoly#32]
**Smartphone (please complete the following information):**
 - Device: Pixel 2 API 29
 - OS: Android 10.0

**Describe the bug**

If you try to start the server, the app crashes and exceptions are thrown. I think this is because the ServerSocket is started on the UI thread and not in the run method, of the GameServer class.

**How to reproduce**

Add this Code in the onCreate method of the MainActivity for testing purposes.
```
	GameServer server = GameServer.getInstance();
		try{
			server.startServer();
			server.allowJoining(getApplicationContext());
			GameController controller = GameController.getInstance();
			controller.connect(server.getAddress(), server.getPort());
		}catch (IOException e){
			e.printStackTrace();
		}catch (GameServerAlreadyRunningException e){
			e.printStackTrace();
		}catch (GameServerNotRunningException e){
			e.printStackTrace();
		}
```
**Expected behavior**

Server should start and the Client on the same device should be able to join.
**Screenshots**

**Additional context**

**Comment by valentingavran** [comment]
Can't program issue #14 further, because to test the new logic starting is essential

**Comment by valentingavran** [comment]
Console Log:
```
04/19 18:59:31: Launching 'app' on Pixel 2 API 29.
$ adb shell am start -n "com.ss20.se2.monopoly/com.ss20.se2.monopoly.MainActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Connected to process 18733 on device 'emulator-5554'.
Capturing and displaying logcat messages from application. This behavior can be disabled in the "Logcat output" section of the "Debugger" settings page.
D/libEGL: Emulator has host GPU support, qemu.gles is set to 1.
W/RenderThread: type=1400 audit(0.0:139): avc: denied { write } for name="property_service" dev="tmpfs" ino=7813 scontext=u:r:untrusted_app:s0:c134,c256,c512,c768 tcontext=u:object_r:property_socket:s0 tclass=sock_file permissive=0
W/libc: Unable to set property "qemu.gles" to "1": connection failed; errno=13 (Permission denied)
D/libEGL: loaded /vendor/lib/egl/libEGL_emulation.so
D/libEGL: loaded /vendor/lib/egl/libGLESv1_CM_emulation.so
D/libEGL: loaded /vendor/lib/egl/libGLESv2_emulation.so
W/20.se2.monopol: Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (greylist, reflection, allowed)
    Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (greylist, reflection, allowed)
W/System.err: java.net.SocketException: socket failed: EPERM (Operation not permitted)
        at java.net.ServerSocket.createImpl(ServerSocket.java:309)
        at java.net.ServerSocket.getImpl(ServerSocket.java:259)
        at java.net.ServerSocket.bind(ServerSocket.java:377)
        at java.net.ServerSocket.<init>(ServerSocket.java:237)
        at java.net.ServerSocket.<init>(ServerSocket.java:128)
        at com.ss20.se2.monopoly.network.server.GameServer.startServer(GameServer.java:45)
        at com.ss20.se2.monopoly.MainActivity.onCreate(MainActivity.java:22)
W/System.err:     at android.app.Activity.performCreate(Activity.java:7802)
        at android.app.Activity.performCreate(Activity.java:7791)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1299)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3245)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3409)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
D/HostConnection: HostConnection::get() New Host Connection established 0xdf04f190, tid 18779
D/HostConnection: HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_YUV420_888_to_NV21 ANDROID_EMU_YUV_Cache ANDROID_EMU_async_unmap_buffer GL_OES_EGL_image_external_essl3 GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_gles_max_version_3_0 
W/OpenGLRenderer: Failed to choose config with EGL_SWAP_BEHAVIOR_PRESERVED, retrying without...
D/eglCodecCommon: setVertexArrayObject: set vao to 0 (0) 0 0
D/EGL_emulation: eglCreateContext: 0xdf01a120: maj 3 min 0 rcv 3
D/EGL_emulation: eglMakeCurrent: 0xdf01a120: ver 3 0 (tinfo 0xdf00f300)
W/Gralloc3: mapper 3.x is not supported
D/HostConnection: createUnique: call
D/HostConnection: HostConnection::get() New Host Connection established 0xdf04f2d0, tid 18779
    HostComposition ext ANDROID_EMU_CHECKSUM_HELPER_v1 ANDROID_EMU_native_sync_v2 ANDROID_EMU_native_sync_v3 ANDROID_EMU_native_sync_v4 ANDROID_EMU_dma_v1 ANDROID_EMU_direct_mem ANDROID_EMU_host_composition_v1 ANDROID_EMU_host_composition_v2 ANDROID_EMU_YUV420_888_to_NV21 ANDROID_EMU_YUV_Cache ANDROID_EMU_async_unmap_buffer GL_OES_EGL_image_external_essl3 GL_OES_vertex_array_object GL_KHR_texture_compression_astc_ldr ANDROID_EMU_gles_max_version_3_0 
D/eglCodecCommon: allocate: Ask for block of size 0x1000
    allocate: ioctl allocate returned offset 0x3ff807000 size 0x2000
D/EGL_emulation: eglMakeCurrent: 0xdf01a120: ver 3 0 (tinfo 0xdf00f300)
D/eglCodecCommon: setVertexArrayObject: set vao to 0 (0) 1 0
```

**Comment by bferijan** [comment]
Problem occured due to old app installed on emulator. 
Deinstalling the app from the emulator, restarting the emulator and installing the app again solved the issue. 
Further reading : https://stackoverflow.com/questions/56266801/java-net-socketexception-socket-failed-eperm-operation-not-permitted

**Comment by valentingavran** [comment]
> Problem occured due to old app installed on emulator.
> Deinstalling the app from the emulator, restarting the emulator and installing the app again solved the issue.
> Further reading : https://stackoverflow.com/questions/56266801/java-net-socketexception-socket-failed-eperm-operation-not-permitted

Confused "uninstalling" the app with "terminating" 🤦🏻‍♂️
